# Generated by Django 4.2.9 on 2026-02-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品类名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='品类编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品类',
                'verbose_name_plural': '品类',
                'db_table': 'wh_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='货物名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='货物编码')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='库存数量')),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='预警阈值')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货物',
                'verbose_name_plural': '货物',
                'db_table': 'wh_goods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='单位名称')),
                ('symbol', models.CharField(blank=True, max_length=20, verbose_name='单位符号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
                'db_table': 'wh_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', '库存不足'), ('expiring', '即将过期'), ('expired', '已过期')], max_length=20, verbose_name='预警类型')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='warehouse.goods', verbose_name='货物')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'db_table': 'wh_warning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品种名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='品种编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='warehouse.category', verbose_name='所属品类')),
            ],
            options={
                'verbose_name': '品种',
                'verbose_name_plural': '品种',
                'db_table': 'wh_variety',
                'ordering': ['-created_at'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='出库数量')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('stock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
                'db_table': 'wh_stock_out',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='入库数量')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('stock_in_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_in_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'db_table': 'wh_stock_in',
                'ordering': ['-stock_in_time'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.unit', verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='goods',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='warehouse.variety', verbose_name='所属品种'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='warehouse.stockout', verbose_name='出库记录')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'db_table': 'wh_approval',
                'ordering': ['-created_at'],
            },
        ),
    ]
