# Generated by Django 4.2.9 on 2026-02-04 12:15

import apps.personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.personnel.models.avatar_upload_path, verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考勤人员',
                'verbose_name_plural': '考勤人员',
                'db_table': 'pm_attendance_person',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.personnel.models.avatar_upload_path, verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '出库人员',
                'verbose_name_plural': '出库人员',
                'db_table': 'pm_stock_out_person',
                'ordering': ['-created_at'],
            },
        ),
    ]
