# Generated by Django 4.2.9 on 2026-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='报表日期')),
                ('in_count', models.IntegerField(default=0, verbose_name='入库次数')),
                ('in_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='入库总量')),
                ('out_count', models.IntegerField(default=0, verbose_name='出库次数')),
                ('out_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='出库总量')),
                ('warning_count', models.IntegerField(default=0, verbose_name='预警数量')),
                ('summary', models.TextField(blank=True, verbose_name='报表摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '每日报表',
                'verbose_name_plural': '每日报表',
                'db_table': 'rp_daily_report',
                'ordering': ['-report_date'],
            },
        ),
    ]
